[package]
name = "lorem-rss"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.8", features = ["macros"] }
chrono = "0.4.42"
fake = "4.4.0"
rss = "2.0.12"
tokio = { version = "1.49.0", features = ["full"] }
